---
Simulation:
  NIID_DATA_SEED: 42
  SAVE_TRAINED_MODELS: False
  TIMESTEP_IN_MIN: 10
  MAX_ROUND_IN_MIN: 60
  MAX_ROUNDS: 10
  MAX_TIME_IN_DAYS: 7
  STOPPING_CRITERIA: None
  NUM_CLIENTS: 100
  CLIENTS_PER_ROUND: 10
  BATCH_SIZE: 10
  EPOCHS: 5
  SOLAR_SIZE: 800

Scenario:
  scenario: "global"
  dataset: "MNIST"
  model: "conv"
  hidden_layers: [64, 128, 256, 256]
  approach: "fedzero_0_1"
  overselect: 1
  forecast_error: "error"
  imbalanced_scenario: False
  seed: None
  beta: 0.1


optim_scheduler:
  optimizer: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 5.00e-04


RAY_CLIENT_RESOURCES:
  num_cpus: 1
  num_gpus: 0

RAY_INIT_ARGS:
  ignore_reinit_error: True
  include_dashboard: False
