Simulation:
  NIID_DATA_SEED: 42
  SAVE_TRAINED_MODELS: False
  TIMESTEP_IN_MIN: 1
  MAX_ROUND_IN_MIN: 60
  MAX_ROUNDS: 10
  MAX_TIME_IN_DAYS: 7
  STOPPING_CRITERIA: None
  NUM_CLIENTS: 100
  CLIENTS_PER_ROUND: 10
  BATCH_SIZE: 10
  EPOCHS: 5
  SOLAR_SIZE: 800

Scenario:
  scenario: "global"
  dataset: "cifar10" # or mnist
  model: "conv"
  hidden_layers: [64, 128, 256, 512]
  track: True
  approach: "fedzero_1_1"
  overselect: 1
  forecast_error: "error"
  imbalanced_scenario: False
  seed: 42
  distribution: Dirichlet #HeteroFL_Non_iid for non-iid distribution defined in HeteroFL
  beta: 0.5
  shared_per_user: 2

client_selection:
  alpha: 1
  exclusion_factor: 1

optim_scheduler:
  optimizer: SGD
  lr: 0.001 # lr: 0.01 for MNIST
  momentum: 0.9
  weight_decay: 5.00e-04

RAY_CLIENT_RESOURCES:
  num_cpus: 1
  num_gpus: 0.3